basePath: /
host: localhost:9090
info:
  contact: {}
  description: Admin API Documentation
  title: Remontai Admin API
  version: "1.0"
paths:
  /api/v1/ping:
    get:
      description: Returns pong message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - health
swagger: "2.0"
